"use client";

import React, { useState, useEffect } from "react";
import { X, Mail, Calendar, Sparkles, Loader2, Paperclip } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

// Actions
import { sendComposeEmailAction } from "@/actions/mail.actions";
import { addCalendarEventAction } from "@/actions/calendar.actions";
import { createProjectUpdateAction } from "@/actions/project.actions";

interface AIToolModalProps {
  isOpen: boolean;
  onClose: () => void;
  toolCall: any; // { name: string, args: any }
  projectId: string;
}

export default function AIToolModal({ isOpen, onClose, toolCall, projectId }: AIToolModalProps) {
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);

  // Form State
  const [formData, setFormData] = useState<any>({});
  
  useEffect(() => {
    if (toolCall?.args) {
      setFormData(toolCall.args);
    }
  }, [toolCall]);

  if (!isOpen || !toolCall) return null;

  const handleAction = async () => {
    setIsLoading(true);
    try {
      if (toolCall.name === "composeEmail") {
        const res = await sendComposeEmailAction(
          projectId,
          formData.to, 
          formData.subject,
          formData.body
        );
        if (res.success) {
          toast({ title: "Email Sent Successfully", description: "Your email is on its way." });
          onClose();
        } else {
          toast({ title: "Error", description: res.error || "Failed to send email", variant: "destructive" });
        }
      } else if (toolCall.name === "createEvent") {
        const res = await addCalendarEventAction(
          projectId,
          {
            title: formData.title,
            description: formData.description || "",
            startTime: new Date(formData.startTime),
            endTime: new Date(formData.endTime)
          }
        );
        if (res.success) {
          toast({ title: "Event Created", description: "Calendar event scheduled." });
          onClose();
        } else {
          toast({ title: "Error", description: res.error || "Failed to create event", variant: "destructive" });
        }
      } else if (toolCall.name === "composeUpdate") {
        const payload = new FormData();
        payload.append("projectId", projectId);
        payload.append("title", formData.title);
        payload.append("details", formData.details);
        
        const res = await createProjectUpdateAction(payload);
        if (res.success) {
          toast({ title: "Update Posted", description: "Your project update is live." });
          onClose();
        } else {
          toast({ title: "Error", description: res.error || "Failed to post update", variant: "destructive" });
        }
      }
    } catch (error: any) {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    } finally {
      setIsLoading(false);
    }
  };

  const getIcon = () => {
    switch (toolCall.name) {
      case "composeEmail": return <Mail className="text-emerald-500" size={24} />;
      case "createEvent": return <Calendar className="text-sky-500" size={24} />;
      case "composeUpdate": return <Sparkles className="text-violet-500" size={24} />;
      default: return <Sparkles className="text-primary" size={24} />;
    }
  };

  const getTitle = () => {
    switch (toolCall.name) {
      case "composeEmail": return "Review Email Draft";
      case "createEvent": return "Review Calendar Event";
      case "composeUpdate": return "Review Project Update";
      default: return "Review Action";
    }
  };

  const getActionLabel = () => {
    switch (toolCall.name) {
      case "composeEmail": return "Send Email";
      case "createEvent": return "Create Event";
      case "composeUpdate": return "Post Update";
      default: return "Confirm";
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-zinc-900/40 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl shadow-xl w-full max-w-2xl overflow-hidden border border-zinc-200 flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-zinc-100 bg-zinc-50/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-white border border-zinc-200 shadow-sm flex items-center justify-center">
              {getIcon()}
            </div>
            <div>
              <h2 className="text-lg font-bold text-zinc-900">{getTitle()}</h2>
              <p className="text-sm text-zinc-500 font-medium">Generated by Kiwiko Agent</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-zinc-400 hover:text-zinc-600 hover:bg-zinc-100 rounded-full transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto flex-1">
          <div className="space-y-4">
            {toolCall.name === "composeEmail" && (
              <>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">To</label>
                  <input 
                    type="email" 
                    value={formData.to || ""} 
                    onChange={e => setFormData({...formData, to: e.target.value})}
                    className="w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Subject</label>
                  <input 
                    type="text" 
                    value={formData.subject || ""} 
                    onChange={e => setFormData({...formData, subject: e.target.value})}
                    className="w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Message Body</label>
                  <textarea 
                    rows={8}
                    value={formData.body || ""} 
                    onChange={e => setFormData({...formData, body: e.target.value})}
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-200 rounded-xl text-sm text-zinc-700 leading-relaxed focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all resize-none"
                  />
                </div>
              </>
            )}

            {toolCall.name === "createEvent" && (
              <>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Event Title</label>
                  <input 
                    type="text" 
                    value={formData.title || ""} 
                    onChange={e => setFormData({...formData, title: e.target.value})}
                    className="w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all"
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Start Time</label>
                    <input 
                      type="datetime-local" 
                      value={formData.startTime ? new Date(formData.startTime).toISOString().slice(0, 16) : ""} 
                      onChange={e => setFormData({...formData, startTime: e.target.value})}
                      className="w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm font-medium text-zinc-700 focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">End Time</label>
                    <input 
                      type="datetime-local" 
                      value={formData.endTime ? new Date(formData.endTime).toISOString().slice(0, 16) : ""} 
                      onChange={e => setFormData({...formData, endTime: e.target.value})}
                      className="w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm font-medium text-zinc-700 focus:outline-none"
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Description</label>
                  <textarea 
                    rows={4}
                    value={formData.description || ""} 
                    onChange={e => setFormData({...formData, description: e.target.value})}
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-200 rounded-xl text-sm text-zinc-700 leading-relaxed focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all resize-none"
                  />
                </div>
              </>
            )}

            {toolCall.name === "composeUpdate" && (
              <>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Update Title</label>
                  <input 
                    type="text" 
                    value={formData.title || ""} 
                    onChange={e => setFormData({...formData, title: e.target.value})}
                    className="w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1.5">Details</label>
                  <textarea 
                    rows={8}
                    value={formData.details || ""} 
                    onChange={e => setFormData({...formData, details: e.target.value})}
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-200 rounded-xl text-sm text-zinc-700 leading-relaxed focus:outline-none focus:ring-2 focus:ring-zinc-900/10 focus:border-zinc-900 transition-all resize-none"
                  />
                </div>
                {/* Minimal Attachment UI simulation */}
                <div className="flex items-center gap-2 px-4 py-3 bg-zinc-50 rounded-xl border border-dashed border-zinc-300">
                    <Paperclip size={16} className="text-zinc-400" />
                    <span className="text-sm font-medium text-zinc-500">Image upload is handled separately in the standard Updates tab. For AI updates, only text is supported currently.</span>
                </div>
              </>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-zinc-100 flex items-center justify-end gap-3 bg-white">
          <button
            onClick={onClose}
            className="px-6 py-2.5 text-sm font-bold text-zinc-600 bg-white border border-zinc-200 rounded-xl hover:bg-zinc-50 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleAction}
            disabled={isLoading}
            className="px-6 py-2.5 text-sm font-bold text-white bg-zinc-900 rounded-xl hover:bg-zinc-800 transition-all shadow-md hover:shadow-lg disabled:opacity-50 flex items-center gap-2"
          >
            {isLoading ? <Loader2 size={16} className="animate-spin" /> : getIcon()}
            {getActionLabel()}
          </button>
        </div>
      </div>
    </div>
  );
}
